---
 
 # ansible playbook to install my dev machine

- name: "install external apps"
  hosts: localhost
  sudo: yes
  roles:
     - { role: theNewFlesh.sublime }
     - { role: henriklynggaard.clion }
     - { role: gantsign.gitkraken }
     


- name: "install using apt"
  hosts: localhost
  sudo: yes
  tasks:
   - apt: name={{ item }} state=present
     with_items:
       - curl
       - gcc
       - python-apport
       - python-lockfile
       - python-requests
       - ubuntu-restricted-extras
       - cgdb
       - iftop
       - htop


- name: Install Dotfiles
  hosts: localhost
  tasks:
    - git: >
         repo=git@github.com/beberlei/vim-dotfiles.git
         dest=/home/${ansible_user_id}/.vim
